# Generated by Django 3.1.6 on 2021-12-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loancategory',
            options={'verbose_name': 'Loan Category', 'verbose_name_plural': 'Loan Categories'},
        ),
    ]
