# Generated by Django 4.0 on 2021-12-27 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211220_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
