# Generated by Django 4.0 on 2021-12-27 05:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_loan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='code',
            field=models.CharField(default=main.models.key_generator, editable=False, max_length=6, unique=True),
        ),
    ]
