# Generated by Django 4.0 on 2022-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_loan_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('investment', models.CharField(blank=True, choices=[('Lender', 'Lender'), ('Private Investor', 'Private Investor'), ('Employer', 'Employer')], default='Lender', max_length=250, null=True)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
