# Generated by Django 4.0 on 2022-01-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallBacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call Back',
                'verbose_name_plural': 'Mpesa Call Backs',
            },
        ),
        migrations.CreateModel(
            name='MpesaCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call',
                'verbose_name_plural': 'Mpesa Calls',
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('type', models.TextField()),
                ('reference', models.TextField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.TextField()),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='IndividualLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanType', models.CharField(blank=True, choices=[('Poverty Reduction Support Loan', 'Poverty Reduction Support Loan'), ('Investment Loan (Sacco)', 'Investment Loan (Sacco)'), ('Agriculture/Farming Loan', 'Agriculture/Farming Loan'), ('Business Loan', 'Business Loan'), ('Church Support', 'Church Support'), ('Schools/Learning Institutions', 'Schools/Learning Institutions'), ('Mitigation assistance', 'Mitigation assistance'), ('EIDL Advance Programs', 'EIDL Advance Programs'), ('Microloan', 'Microloan')], default='Poverty Reduction Support Loan', max_length=250, null=True)),
                ('grant', models.CharField(blank=True, max_length=50, null=True)),
                ('loanReq', models.CharField(blank=True, max_length=500, null=True)),
                ('Names', models.CharField(blank=True, max_length=200, null=True)),
                ('idNumber', models.IntegerField(blank=True, null=True)),
                ('loanCheck', models.CharField(blank=True, max_length=100, null=True)),
                ('employmentST', models.CharField(blank=True, choices=[('Unemployed', 'Unemployed'), ('Government Employee', 'Government Employee'), ('Full-Time Empoyee', 'Full-Time Empoyee'), ('Part-Time Employee', 'Part-Time Employee'), ('Independent contractor', 'Independent contractor'), ('Self Employed', 'Self Employed')], default='Unemployed', max_length=250, null=True)),
                ('gmonthlyIncome', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('fundUse', models.CharField(blank=True, max_length=300, null=True)),
                ('detFundUse', models.TextField(blank=True, max_length=1000, null=True)),
                ('paymentplan', models.CharField(blank=True, max_length=500, null=True)),
                ('additionalinfo', models.TextField(blank=True, max_length=1000, null=True)),
                ('disbursement', models.CharField(blank=True, choices=[('Lampsum', 'Lampsum'), ('Milestone', 'Milestone')], default='Milestone', max_length=250, null=True)),
                ('desBank', models.CharField(blank=True, max_length=500, null=True)),
                ('accNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanType', models.CharField(blank=True, choices=[('Poverty Reduction Support Loan', 'Poverty Reduction Support Loan'), ('Investment Loan (Sacco)', 'Investment Loan (Sacco)'), ('Agriculture/Farming Loan', 'Agriculture/Farming Loan'), ('Business Loan', 'Business Loan'), ('Church Support', 'Church Support'), ('Schools/Learning Institutions', 'Schools/Learning Institutions'), ('Mitigation assistance', 'Mitigation assistance'), ('EIDL Advance Programs', 'EIDL Advance Programs'), ('Microloan', 'Microloan')], default='Poverty Reduction Support Loan', max_length=250, null=True)),
                ('businessDesc', models.CharField(blank=True, max_length=500, null=True)),
                ('loanReq', models.CharField(blank=True, max_length=500, null=True)),
                ('Names', models.CharField(blank=True, max_length=500, null=True)),
                ('BusinessNumber', models.IntegerField(blank=True, null=True)),
                ('NonProfit', models.CharField(blank=True, max_length=500, null=True)),
                ('Franchise', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.CharField(blank=True, choices=[('Limited Liability Company', 'Limited Liability Company'), ('Sole Proprietorship', 'Sole Proprietorship'), ('C-Corporation', 'C-Corporation'), ('S-Corporation', 'S-Corporation'), ('General Patnership', 'General Patnership'), ('Limited Liability Patnership', 'Limited Liability Patnership'), ('Limited Partnership', 'Limited Partnership'), ('Cooperative', 'Cooperative'), ('Trust', 'Trust'), ('Self-help Group', 'Self-help Group'), ('Independent Contractor', 'Independent Contractor'), ('Other', 'Other')], default='Sole Proprietorship', max_length=150, null=True)),
                ('activity', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Automotive Repair', 'Automotive Repair'), ('Automotive Sales & Gas Service Stations', 'Automotive Sales & Gas Service Stations'), ('Business Services', 'Business Services'), ('Communications', 'Communications'), ('Constructions & Contractors', 'Constructions & Contractors'), ('Restaurants', 'Restaurants'), ('Educational Services', 'Educational Services'), ('Entertainment Services', 'Entertainment Services'), ('Educational/Scientific Research', 'Educational/Scientific Research'), ('Finance', 'Finance'), ('Food & Beverage Stores', 'Food & Beverage Stores'), ('Freight', 'Freight'), ('Health Services', 'Health Services'), ('Insurance', 'Insurance'), ('Legal Services', 'Legal Services'), ('Manufacturing', 'Manufacturing'), ('Mining & Ntural Resource Extraction', 'Mining & Ntural Resource Extractio'), ('Miscellaneous Services', 'Miscellaneous Services'), ('Other', 'Other')], default='Agriculture', max_length=150, null=True)),
                ('detActivity', models.TextField(blank=True, max_length=5000, null=True)),
                ('branches', models.IntegerField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('PrimarySOI', models.CharField(blank=True, max_length=500, null=True)),
                ('GrossIncome', models.IntegerField(blank=True, null=True)),
                ('AdditionalSOI', models.CharField(blank=True, max_length=500, null=True)),
                ('MonthExp', models.IntegerField(blank=True, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('BusinessPhone', models.CharField(blank=True, max_length=500, null=True)),
                ('AlternativePhone', models.CharField(blank=True, max_length=500, null=True)),
                ('BusinessEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('BusinessWeb', models.CharField(blank=True, max_length=500, null=True)),
                ('BusinessAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('OwnerName', models.CharField(blank=True, max_length=500, null=True)),
                ('PercOfOwn', models.IntegerField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('information', models.TextField(blank=True, max_length=500, null=True)),
                ('paymentplan', models.CharField(blank=True, max_length=500, null=True)),
                ('desBank', models.CharField(blank=True, max_length=500, null=True)),
                ('accNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('regFee', models.IntegerField(blank=True, null=True)),
                ('VAT', models.IntegerField(blank=True, null=True)),
                ('ExciseDuty', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
